export const site = {
  name: 'AgricX',
  tagline: 'Precision drones and smart equipment for the future of agriculture.',
  email: 'hello@agricx.com',
  phone: '+234 800 000 0000',
  address: '12 Harvest Avenue, Abuja, Nigeria',
};

export const nav = [
  { href: '/', label: 'Home' },
  { href: '/drones', label: 'Drones' },
  { href: '/how-it-works', label: 'How It Works' },
  { href: '/services', label: 'Services' },
  { href: '/blog', label: 'Blog' },
  { href: '/about', label: 'About' },
];

export const products = [
  {
    slug: 'agras-t50',
    name: 'DJI Agras T50',
    category: 'Spraying',
    image: 'agras-drone.jpg',
    gallery: ['agras-drone.jpg', 'drone-sunset.jpg', 'drone-spray-tall.jpg'],
    price: 1880,
    oldPrice: 2100,
    badge: '-15%',
    rating: 4.9,
    short: 'Fully automatic and manual operation, orchard mode, variable rate application.',
    description:
      'The Agras T50 is our flagship spraying drone. A coaxial twin-rotor propulsion system and a split-type torque-resistant structure give it stable flight while carrying up to 40 kg of spray liquid or 50 kg of granules. Dual atomizing centrifugal sprinklers deliver an even droplet size for consistent coverage on fields, orchards and terraces.',
    specs: {
      'Max Payload': '40 kg spray / 50 kg spread',
      'Flow Rate': 'Up to 24 L/min',
      'Spray Width': '4 – 11 m',
      'Flight Time': '≈ 18 min (full load)',
      'Battery': 'DB1560 Intelligent Flight Battery',
      'Obstacle Sensing': 'Active phased-array radar + binocular vision',
    },
  },
  {
    slug: 'mavic-3m',
    name: 'DJI Mavic 3M',
    category: 'Mapping',
    image: 'mavic-drone.jpg',
    gallery: ['mavic-drone.jpg', 'drone-field.jpg', 'field-rows.jpg'],
    price: 1880,
    oldPrice: 2100,
    badge: '-10%',
    rating: 4.8,
    short: 'Multispectral imaging for crop-health maps and precise prescription plans.',
    description:
      'The Mavic 3M pairs a 20 MP RGB camera with four 5 MP multispectral cameras and a sunlight sensor. Fly a survey in the morning and have NDVI crop-health maps ready by lunch, then send prescription maps straight to your spraying fleet.',
    specs: {
      'Cameras': '20 MP RGB + 4 × 5 MP multispectral',
      'Flight Time': '43 min',
      'Coverage': 'Up to 200 ha per flight',
      'Positioning': 'RTK centimeter-level',
      'Weight': '951 g',
      'Transmission': 'O3 Enterprise, 15 km',
    },
  },
  {
    slug: 'agras-t25',
    name: 'DJI Agras T25',
    category: 'Spraying',
    image: 'drone-sunset.jpg',
    gallery: ['drone-sunset.jpg', 'agras-drone.jpg', 'drone-tractor.jpg'],
    price: 1450,
    oldPrice: 1690,
    badge: '-14%',
    rating: 4.8,
    short: 'Compact, single-operator spraying drone for small and mid-sized farms.',
    description:
      'Light enough for one person to carry and deploy, the Agras T25 brings the T50’s spraying technology to smaller plots. It folds down to fit in a pickup bed and is ready to fly in minutes.',
    specs: {
      'Max Payload': '20 kg spray / 25 kg spread',
      'Flow Rate': 'Up to 16 L/min',
      'Spray Width': '4 – 7 m',
      'Flight Time': '≈ 20 min',
      'Folded Size': '1105 × 552 × 595 mm',
      'Obstacle Sensing': 'Phased-array radar',
    },
  },
  {
    slug: 'phantom-4-multispectral',
    name: 'Phantom 4 Multispectral',
    category: 'Mapping',
    image: 'phantom-drone.jpg',
    gallery: ['phantom-drone.jpg', 'field-rows.jpg', 'drone-field.jpg'],
    price: 980,
    oldPrice: 1150,
    badge: '-15%',
    rating: 4.7,
    short: 'Proven survey platform for plant-level vegetation analysis.',
    description:
      'The Phantom 4 Multispectral captures plant-level detail with six integrated cameras. A great entry point for agronomists starting with data-driven crop management.',
    specs: {
      'Cameras': '1 RGB + 5 multispectral',
      'Flight Time': '27 min',
      'Positioning': 'RTK, 1 cm + 1 ppm',
      'Max Speed': '50 km/h',
      'Weight': '1487 g',
      'Transmission': 'OcuSync, 7 km',
    },
  },
  {
    slug: 'agricx-scout-x1',
    name: 'AgricX Scout X1',
    category: 'Monitoring',
    image: 'drone-closeup.jpg',
    gallery: ['drone-closeup.jpg', 'field-rows.jpg', 'drone-tractor.jpg'],
    price: 1290,
    oldPrice: 1450,
    badge: 'New',
    rating: 4.9,
    short: 'Low-altitude scouting drone with a thermal and zoom camera pod.',
    description:
      'Built for row crops, the Scout X1 flies just above the canopy to spot pests, irrigation leaks and nutrient stress early. Its thermal and 30× zoom camera pod lets you inspect individual plants without walking the field.',
    specs: {
      'Camera Pod': 'Thermal 640 × 512 + 30× zoom',
      'Flight Time': '38 min',
      'Wind Resistance': '12 m/s',
      'Positioning': 'GNSS + RTK',
      'IP Rating': 'IP55',
      'Transmission': '10 km',
    },
  },
  {
    slug: 'boom-sprayer-bs400',
    name: 'Boom Sprayer BS-400',
    category: 'Ground',
    image: 'tractor-sprayer.jpg',
    gallery: ['tractor-sprayer.jpg', 'tractor-spray.jpg', 'field-rows.jpg'],
    price: 2450,
    oldPrice: 2800,
    badge: '-12%',
    rating: 4.6,
    short: 'Tractor-mounted 400 L sprayer with a 12 m folding boom.',
    description:
      'For blocks too large for a single drone, the BS-400 mounts to any compact tractor with a 3-point hitch. Pair it with AgricX prescription maps for variable-rate ground application.',
    specs: {
      'Tank': '400 L polyethylene',
      'Boom Width': '12 m folding',
      'Nozzles': '24 anti-drip',
      'Pump': 'Diaphragm, 100 L/min',
      'Hitch': 'Category I / II, 3-point',
      'Control': 'In-cab section control',
    },
  },
  {
    slug: 'precision-planter-p12',
    name: 'Precision Planter P12',
    category: 'Ground',
    image: 'smart-farm.jpg',
    gallery: ['smart-farm.jpg', 'tractor-spray.jpg', 'drone-tractor.jpg'],
    price: 5600,
    oldPrice: 6200,
    badge: '-10%',
    rating: 4.7,
    short: '12-row seed planter with GPS-guided singulation and depth control.',
    description:
      'The P12 places every seed at the right spacing and depth. GPS-guided row shut-off prevents overlaps and works with drone-generated field boundaries out of the box.',
    specs: {
      'Rows': '12',
      'Row Spacing': '45 – 90 cm adjustable',
      'Seed Hopper': '12 × 60 L',
      'Guidance': 'GPS row shut-off',
      'Depth Control': 'Hydraulic, per-row',
      'Required Power': '120+ hp',
    },
  },
];

export const posts = [
  {
    slug: 'remove-prop-guards-change-propellers',
    title: 'How to Remove Prop Guards & Change Propellers',
    category: 'Guidelines',
    image: 'drone-closeup.jpg',
    date: 'Sep 18, 2026',
    read: '5 min read',
    excerpt: 'A step-by-step guide to swapping propellers safely and keeping your drone flying at peak efficiency.',
  },
  {
    slug: 'precision-spraying-pilots-2026',
    title: 'Meet the Precision Spraying Pilots Leading 2026',
    category: 'Events',
    image: 'field-rows.jpg',
    date: 'Sep 04, 2026',
    read: '6 min read',
    excerpt: 'From cocoa farms to rice paddies, these operators are setting new benchmarks for drone application.',
  },
  {
    slug: 'choosing-sd-card-for-mapping',
    title: 'Choosing the Right SD Card for Multispectral Mapping',
    category: 'Technical',
    image: 'drone-field.jpg',
    date: 'Aug 27, 2026',
    read: '4 min read',
    excerpt: 'Write speeds, capacity and durability: what actually matters when your drone captures thousands of images.',
  },
  {
    slug: 'drone-vs-tractor-spraying',
    title: 'Drone vs Tractor Spraying: Which Saves More?',
    category: 'Guidelines',
    image: 'tractor-spray.jpg',
    date: 'Aug 12, 2026',
    read: '7 min read',
    excerpt: 'We compared water use, chemical savings and soil compaction across a full season.',
  },
  {
    slug: 'drones-cut-fertilizer-costs',
    title: '5 Ways Drones Cut Fertilizer Costs',
    category: 'Technical',
    image: 'drone-spray-tall.jpg',
    date: 'Jul 30, 2026',
    read: '5 min read',
    excerpt: 'Variable-rate application and early stress detection mean you only feed the plants that need it.',
  },
  {
    slug: 'planning-your-first-drone-survey',
    title: 'Planning Your First Drone Survey',
    category: 'Events',
    image: 'drone-tractor.jpg',
    date: 'Jul 15, 2026',
    read: '6 min read',
    excerpt: 'Flight altitude, overlap, timing and weather: everything you need before your first mapping mission.',
  },
];
